USE [master]
GO

CREATE DATABASE [Procedures]
GO
ALTER DATABASE [Procedures] SET COMPATIBILITY_LEVEL = 150
GO
ALTER DATABASE [Procedures] SET ANSI_NULL_DEFAULT OFF
GO
ALTER DATABASE [Procedures] SET ANSI_NULLS OFF
GO
ALTER DATABASE [Procedures] SET ANSI_PADDING OFF
GO
ALTER DATABASE [Procedures] SET ANSI_WARNINGS OFF
GO
ALTER DATABASE [Procedures] SET ARITHABORT OFF
GO
ALTER DATABASE [Procedures] SET AUTO_CLOSE OFF
GO
ALTER DATABASE [Procedures] SET AUTO_SHRINK OFF
GO
ALTER DATABASE [Procedures] SET AUTO_UPDATE_STATISTICS ON
GO
ALTER DATABASE [Procedures] SET CURSOR_CLOSE_ON_COMMIT OFF
GO
ALTER DATABASE [Procedures] SET CURSOR_DEFAULT  GLOBAL
GO
ALTER DATABASE [Procedures] SET CONCAT_NULL_YIELDS_NULL OFF
GO
ALTER DATABASE [Procedures] SET NUMERIC_ROUNDABORT OFF
GO
ALTER DATABASE [Procedures] SET QUOTED_IDENTIFIER OFF
GO
ALTER DATABASE [Procedures] SET RECURSIVE_TRIGGERS OFF
GO
ALTER DATABASE [Procedures] SET  DISABLE_BROKER
GO
ALTER DATABASE [Procedures] SET AUTO_UPDATE_STATISTICS_ASYNC OFF
GO
ALTER DATABASE [Procedures] SET DATE_CORRELATION_OPTIMIZATION OFF
GO
ALTER DATABASE [Procedures] SET TRUSTWORTHY OFF
GO
ALTER DATABASE [Procedures] SET ALLOW_SNAPSHOT_ISOLATION OFF
GO
ALTER DATABASE [Procedures] SET PARAMETERIZATION SIMPLE
GO
ALTER DATABASE [Procedures] SET READ_COMMITTED_SNAPSHOT OFF
GO
ALTER DATABASE [Procedures] SET HONOR_BROKER_PRIORITY OFF
GO
ALTER DATABASE [Procedures] SET RECOVERY FULL
GO
ALTER DATABASE [Procedures] SET  MULTI_USER
GO
ALTER DATABASE [Procedures] SET PAGE_VERIFY CHECKSUM
GO
ALTER DATABASE [Procedures] SET DB_CHAINING OFF
GO
ALTER DATABASE [Procedures] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF )
GO
ALTER DATABASE [Procedures] SET TARGET_RECOVERY_TIME = 60 SECONDS
GO
ALTER DATABASE [Procedures] SET DELAYED_DURABILITY = DISABLED
GO
ALTER DATABASE [Procedures] SET QUERY_STORE = OFF
GO
ALTER DATABASE [Procedures] SET  READ_WRITE
GO

USE [Procedures]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE USER ProceduresTest FOR LOGIN ProceduresTest;
GO
GRANT ALTER ANY SCHEMA to ProceduresTest
GO
GRANT EXECUTE to ProceduresTest
GO
GRANT ALL to ProceduresTest
GO
EXEC sp_addrolemember N'db_datareader', N'ProceduresTest'
GO
EXEC sp_addrolemember N'db_datawriter', N'ProceduresTest'
GO
EXEC sp_addrolemember N'db_ddladmin', N'ProceduresTest'
GO
